# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Postgres
spring.profiles.active=local
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

#spring.datasource.url = jdbc:postgresql://dpg-d9fb6lrtqb8s73cngd10-a.oregon-postgres.render.com/donadores_y_entidades_sfbs?sslmode=require
#spring.datasource.username = donadores_y_entidades_sfbs_user
#spring.datasource.password = secZfq56v4ahSLzxE9G1NfVXV12CHvuk

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# DevTools Configuration
spring.devtools.restart.enabled=true

# Server Configuration for Dockerfile
server.port=${PORT:8080}

# DataDog
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=${DATADOG_API_KEY}
management.datadog.metrics.export.step=1m
management.metrics.tags.application=DonadoresYEntidades
spring.jpa.properties.hibernate.generate_statistics=true
spring.datasource.hikari.pool-name=HikariPool-1
