# H2 Database Configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Console
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console

# JPA/Hibernate Configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update

# Postgres
spring.profiles.active=local
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Actuator Configuration
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always

# Logging
logging.level.root=WARN
logging.level.ar.edu.utn.dds.k3003=INFO
spring.application.name = ${SPRING_APPLICATION_NAME}
spring.jpa.open-in-view=false

# DevTools Configuration
spring.devtools.restart.enabled=false

# Server Configuration for Dockerfile
server.port=${PORT:8080}

# DataDog
management.datadog.metrics.export.enabled=true
management.datadog.metrics.export.api-key=${DATADOG_API_KEY}
management.datadog.metrics.export.step=1m
management.metrics.tags.application=DonadoresYEntidades
spring.jpa.properties.hibernate.generate_statistics=true
spring.datasource.hikari.pool-name=HikariPool-1
